#!/usr/bin/env node
/**
 * Generate everything derived from data/.
 *
 *   README.md                            the list itself
 *   .github/ISSUE_TEMPLATE/add-entry.yml the submission form
 *
 * data/ is the source of truth; everything between the generated markers in
 * README.md is rebuilt from it, and prose outside the markers is hand-written
 * and left alone. The issue form is generated in full, so its category dropdown
 * cannot drift from data/categories/.
 *
 *   node scripts/build.js           # rewrite the generated files
 *   node scripts/build.js --check   # fail if they would change (CI)
 */

import fs from "node:fs";
import path from "node:path";

import { ROOT, loadCategories, loadSections, renderRow } from "./data.js";
import { FIELDS } from "./issue-entry.js";

const README = path.join(ROOT, "README.md");
const ISSUE_FORM = path.join(ROOT, ".github", "ISSUE_TEMPLATE", "add-entry.yml");
const START = "<!-- BEGIN ENTRIES -->";
const END = "<!-- END ENTRIES -->";
const TOC_START = "<!-- BEGIN TOC -->";
const TOC_END = "<!-- END TOC -->";

function anchor(title) {
  return title.toLowerCase().replace(/[^a-z0-9 -]/g, "").replace(/ /g, "-");
}

const HEADER = ["Project", "What it replaces"];

/**
 * Render one category as a pipe-aligned table.
 *
 * The padding is not cosmetic: awesome-lint's table-pipe-alignment rule rejects
 * ragged cells, and hand-aligning 116 rows would be unmaintainable. Since the
 * page is generated, the builder does it.
 *
 * Widths are measured the way remark-lint measures them, in UTF-16 units.
 */
function table(entries) {
  const rows = [HEADER, ...entries.map(renderRow)];
  // UTF-16 length, not code points. remark-lint measures cells that way, and an
  // astral character disagrees: 🧡 is one code point but two units, so padding by
  // code points left every row containing it one short of aligned.
  const widths = HEADER.map((_, i) => Math.max(...rows.map((r) => r[i].length)));
  const pad = (cells) =>
    `| ${cells.map((c, i) => c + " ".repeat(widths[i] - c.length)).join(" | ")} |`;
  const rule = `| ${widths.map((n) => "-".repeat(n)).join(" | ")} |`;
  return [pad(rows[0]), rule, ...rows.slice(1).map(pad)].join("\n");
}

function build(sections) {
  return sections
    .map((s) => `## ${s.name}\n\n${table(s.entries)}`)
    .join("\n\n");
}

/**
 * awesome-lint requires the contents to be the first section and to list every
 * h2 on the page -- not just the categories. Reading them back off the
 * assembled README keeps the two in step automatically.
 */
function tableOfContents(markdown) {
  return markdown
    .split("\n")
    .filter((line) => line.startsWith("## "))
    .map((line) => line.slice(3).trim())
    // awesome-lint builds its expected contents from the headings but omits
    // "Contributing", so listing it here reads as an off-by-one mismatch
    // against every section after it.
    .filter((title) => title !== "Contents" && title !== "Contributing")
    .map((title) => `- [${title}](#${anchor(title)})`)
    .join("\n");
}

function escapeRe(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function splice(text, start, end, body) {
  const re = new RegExp(`${escapeRe(start)}[\\s\\S]*?${escapeRe(end)}`);
  return text.replace(re, `${start}\n\n${body}\n\n${end}`);
}

function issueForm(categories) {
  const options = categories.map((c) => `        - "${c.name}"`).join("\n");
  return `# Generated by scripts/build.js from data/categories/ -- do not edit by hand.
name: Add an entry
description: Suggest an app for the list
title: "Add: owner/repo"
labels: ["submission"]
body:
  - type: markdown
    attributes:
      value: |
        The list is generated from \`data/\`, so there is no file for you to write.
        Fill this in and a bot checks the repository, builds the entry and opens the
        pull request.

        It checks the things a machine can decide: an open-source license (or none,
        which gets listed with a warning), a Cloudflare deploy configuration, recent
        activity, and that it isn't already listed. Whether the project is genuinely a
        SaaS replacement rather than a framework or template is a human call, made in
        review.

  - type: input
    id: repo
    attributes:
      label: ${FIELDS.repo}
      description: A GitHub repository, as \`owner/name\` or a full URL.
      placeholder: owner/name
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: ${FIELDS.category}
      description: Where it belongs in the list.
      options:
${options}
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: ${FIELDS.summary}
      description: >-
        One sentence, on one line. Lead with the product it stands in for when there is
        an obvious one. Say what it does, not how it feels about it -- no "blazing fast",
        no "modern", no "simple".
      placeholder: Calendly alternative for a single team, with booking pages rendered at the edge.
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: ${FIELDS.notes}
      description: >-
        Optional. Tell us if you maintain this project -- that is welcome, it just goes
        on the record. Also the place to explain an unusual deploy setup.
    validations:
      required: false
`;
}

function writeOrCheck(file, contents, check, changed) {
  const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
  if (check) {
    if (current !== contents) changed.push(path.relative(ROOT, file));
    return;
  }
  if (current !== contents) fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, contents);
}

function main() {
  const check = process.argv.includes("--check");
  const categories = loadCategories();
  const sections = loadSections();
  const entries = sections.flatMap((s) => s.entries);
  const body = build(sections);
  const changed = [];

  const current = fs.readFileSync(README, "utf8");
  // Entries first: the contents are derived from the finished page.
  let updated = splice(current, START, END, body);
  updated = splice(updated, TOC_START, TOC_END, tableOfContents(updated));

  const unlicensed = entries.filter((e) => !e.license).length;

  writeOrCheck(README, updated, check, changed);
  writeOrCheck(ISSUE_FORM, issueForm(categories), check, changed);

  if (check) {
    if (changed.length) {
      console.log(`Out of date: ${changed.join(", ")} -- run: npm run build`);
      return 1;
    }
    console.log(`Generated files are current (${entries.length} entries)`);
    return 0;
  }

  console.log(
    `Wrote README.md (${entries.length} entries, ${unlicensed} without a license) ` +
      `and the issue form (${categories.length} categories)`,
  );
  return 0;
}

process.exit(main());
